 name: aliyun-oss-website-action
  # You may pin to the exact commit or the version.
  # uses: fangbinwei/aliyun-oss-website-action@73062d4b8ab558c81c2325970e1023099391b43b
  uses: fangbinwei/aliyun-oss-website-action@v1.3.0
  with:
    # Folder which contains the website files
    folder: oss://blog/
    # Exclude file from the folder
    exclude: # optional
    # Aliyun OSS accessKeyId.
    accessKeyId: ${{ secrets.ID }}
    # Aliyun OSS accessKeySecret.
    accessKeySecret: ${{ secrets.SE }}
    # Aliyun OSS bucket instance.
    bucket: hknewblog
    # OSS region domain
    endpoint: oss-cn-hongkong.aliyuncs.com
    # `true` to identify the endpoint is your custom domain.
    cname: # optional, default is false
    # `true` to skip setting static pages related configuration. `indexPage`, `notFoundPage` will not be used.
    skipSetting: # optional, default is false
    # Save info of uploaded files to increase next upload speed
    incremental: # optional, default is true
    # index page
    indexPage: # optional, default is index.html
    # not found page
    notFoundPage: # optional, default is 404.html
    # Cache-Control for HTML
    htmlCacheControl: # optional, default is no-cache
    # Cache-Control for image
    imageCacheControl: # optional, default is max-age=864000
    # Cache-Control for other files
    otherCacheControl: # optional, default is max-age=2592000
